services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "3500:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
  backend:
    build: 
       dockerfile: Dockerfile.dev
       context: ./backend
    volumes:
      - /home/node/app/node_modules
      - ./backend:/home/node/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
  testbackend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /home/node/app/node_modules
      - ./backend:/home/node/app
    command: ["npm", "run", "test"]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./frontend:/home/node/app
    ports:
      - "3001:3001"
  testfrontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /home/node/app/node_modules
      - ./frontend:/home/node/app
    command: ["npm", "run", "test"]

volumes:
  db_data: